### ISSUE TITLE
Add a PHP version requirement in composer.json?

### ISSUE THREAD

**Issue by tttttony** [dalpras/oauth2-gotowebinar#2]
First, thank you so much for this package, It helped a lot to fix a broken site upgrade to the new API

Took me an embarrassing amount of time to notice the reason this package was blowing up is the system I was updating was on PHP 5.x 

Once I moved the site to 7.3 it worked GREAT!

Would have help find this sooner with a php version requirement in the composer.json

Thanks!

**Comment by dalpras** [comment]
thanks for feedback, now fixed
