### ISSUE TITLE
Error during creation of Webinar

### ISSUE THREAD

**Issue by Srinivasysr2003** [dalpras/oauth2-gotowebinar#5]
Hi Team,

Facing an issue while creating webinar using code provided in your example.  getWebinars() is returning fine which I have commented.

Code is as below.
**************************************************
try {
 //       $data = $resWebinar->getWebinars();
	$dateUtcHelper = new \DalPraS\OAuth2\Client\Helper\DateUtcHelper();
        $data =  $resWebinar->createWebinar([
                "subject" => "My first webinar",
                "times" => [[
                    "startTime" => $dateUtcHelper->date2utc(new \DateTime('+1 day')),
                    "endTime" => $dateUtcHelper->date2utc(new \DateTime('+2 days')),
                ]],
            ]);
	return json_encode($data);
}  catch (GotoWebinarProviderException $e) {
        // return a psr7 response message (using for example zend\diactoros)
        //return $e->generateHttpResponse(new \Zend\Diactoros\Response());
      //return json_encode($data);
    } catch (\Exception $e) {
	echo("Test Exception");
        echo var_dump($e->getMessage());
	die($e);

    }
**************************************************

Error is as below & not getting any clue from anywhere.  Could you please let us know, if you know anything mistake from my end.
***************************************************
Test Exceptionstring(22) "RequestValidationError" DalPraS\OAuth2\Client\Provider\Exception\GotoWebinarProviderException: RequestValidationError in /var/www/html/vendor/dalpras/oauth2-gotowebinar/src/Provider/Exception/GotoWebinarProviderException.php:61 Stack trace: #0 /var/www/html/vendor/dalpras/oauth2-gotowebinar/src/Provider/Exception/GotoWebinarProviderException.php(35): DalPraS\OAuth2\Client\Provider\Exception\GotoWebinarProviderException::fromResponse(Object(GuzzleHttp\Psr7\Response), 'RequestValidati...') #1 /var/www/html/vendor/dalpras/oauth2-gotowebinar/src/Provider/GotoWebinar.php(133): DalPraS\OAuth2\Client\Provider\Exception\GotoWebinarProviderException::clientException(Object(GuzzleHttp\Psr7\Response), Array) #2 /var/www/html/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(628): DalPraS\OAuth2\Client\Provider\GotoWebinar->checkResponse(Object(GuzzleHttp\Psr7\Response), Array) #3 /var/www/html/vendor/dalpras/oauth2-gotowebinar/src/Resources/Webinar.php(224): League\OAuth2\Client\Provider\AbstractProvider->getParsedResponse(Object(GuzzleHttp\Psr7\Request)) #4 /var/www/html/GoToWebinar_dalpras.php(98): DalPraS\OAuth2\Client\Resources\Webinar->createWebinar(Array) #5 {main}
****************************************************

Thanks,
Srinivas

**Comment by techouse** [comment]
I think you will need to format your dates to the format laid out here https://developer.goto.com/GoToWebinarV2/#operation/createWebinar, so something like

```php
[
    "startTime" => (new DateTime)->setTimeZone(new DateTimeZone('Z'))->format('Y-m-d\TH:i:sT'),
    "endTime" => (new DateTime('+2 hours'))->setTimeZone(new DateTimeZone('Z'))->format('Y-m-d\TH:i:sT'),
]
```

**Comment by Srinivasysr2003** [comment]
Hi Klemen,
I have tried and code looks like below.  Can someone run the code and provide exact root cause to fix it?*********************************************$data =  $resWebinar->createWebinar([
   "subject" => "My first webinar",   "Content-Type" => "application/x-www-form-urlencoded",   "times" => [      [         "startTime" => "2020-10-09T05:50:46Z",         "endTime" => "2020-10-09T05:50:46Z"      ]   ]
]);
*********************************************
but still I get below error and no luck.*********************************************DalPraS\OAuth2\Client\Provider\Exception\GotoWebinarProviderException: RequestValidationError in /var/www/html/vendor/dalpras/oauth2-gotowebinar/src/Provider/Exception/GotoWebinarProviderException.php:61 Stack trace: #0 /var/www/html/vendor/dalpras/oauth2-gotowebinar/src/Provider/Exception/GotoWebinarProviderException.php(35): DalPraS\OAuth2\Client\Provider\Exception\GotoWebinarProviderException::fromResponse(Object(GuzzleHttp\Psr7\Response), 'RequestValidati...') #1 /var/www/html/vendor/dalpras/oauth2-gotowebinar/src/Provider/GotoWebinar.php(133): DalPraS\OAuth2\Client\Provider\Exception\GotoWebinarProviderException::clientException(Object(GuzzleHttp\Psr7\Response), Array) #2 /var/www/html/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(628): DalPraS\OAuth2\Client\Provider\GotoWebinar->checkResponse(Object(GuzzleHttp\Psr7\Response), Array) #3 /var/www/html/vendor/dalpras/oauth2-gotowebinar/src/Resources/Webinar.php(224): League\OAuth2\Client\Provider\AbstractProvider->getParsedResponse(Object(GuzzleHttp\Psr7\Request)) #4 /var/www/html/GoToWebinar_dalpras.php(129): DalPraS\OAuth2\Client\Resources\Webinar->createWebinar(Array) #5 {main}

*********************************************
Thanks,Srinivas

    On Friday, October 9, 2020, 12:16:07 AM GMT+5:30, Klemen Tusar <notifications@github.com> wrote:  
 
 


I think you will need to format your dates to the format laid out here https://developer.goto.com/GoToWebinarV2/#operation/createWebinar, so something like
[
    "startTime" => (new DateTime)->setTimeZone(new DateTimeZone('Z'))->format('Y-m-d\TH:i:sT'),
    "endTime" => (new DateTime('+2 hours'))->setTimeZone(new DateTimeZone('Z'))->format('Y-m-d\TH:i:sT'),
]

**Comment by Srinivasysr2003** [comment]
Hi,
Even I have tried with dates in Nov month and did not succeed.  I am getting same error message as above.

         "startTime" => "2020-11-09T05:50:46Z",
         "endTime" => "2020-11-09T05:50:46Z"

Thanks,
Srinivas

**Comment by techouse** [comment]
Yes well, one obvious thing GoTo will not tell you is that the dates need to be in the future. 🤣 

As for your error, I can't really help you much if you don't catch the error response.

P.S. Try to use GitHub's markdown to properly format your errors because what you just pasted is quite illegible.

**Comment by Srinivasysr2003** [comment]
> Yes well, one obvious thing GoTo will not tell you is that the dates need to be in the future. 🤣
> 
> As for your error, I can't really help you much if you don't catch the error response.
> 
> P.S. Try to use GitHub's markdown to properly format your errors because what you just pasted is quite illegible.

I am sorry for the comment as I replied from my yahoo email and format was corrupted.  Now I have edited my comment in GitHub and now you can see the error properly.

Thank you for your help.
