### ISSUE TITLE
Not getting this to work, is it still valid?

### ISSUE THREAD

**Issue by inpresif** [dalpras/oauth2-gotowebinar#7]
Been trying to get this to work on 2 accounts. Thr accessToken section works fine, but not getting any of the webinardata back.

For this call:
`$resWebinar = new \DalPraS\OAuth2\Client\Resources\Webinar($provider, $accessToken);`

We set the retrieved accessToken as the 2nd parameter, which results in this error:

`Fatal error: Uncaught TypeError: Argument 2 passed to DalPraS\OAuth2\Client\Resources\AuthenticatedResourceAbstract::__construct() must be an instance of League\OAuth2\Client\Token\AccessToken, string given, called in https://localhost.io\go2webinar\demo-features.php on line 31 and defined in https://localhost.io\go2webinar\vendor\dalpras\oauth2-gotowebinar\src\Resources\AuthenticatedResourceAbstract.php:27 Stack trace: #0 https://localhost.io\go2webinar\demo-features.php(31): DalPraS\OAuth2\Client\Resources\AuthenticatedResourceAbstract->__construct(Object(DalPraS\OAuth2\Client\Provider\GotoWebinar), 'eyJraWQiOiJvYXV...') #1 {main} thrown in https://localhost.io\go2webinar\vendor\dalpras\oauth2-gotowebinar\src\Resources\AuthenticatedResourceAbstract.php on line 27`

Is this not the correct method?

**Comment by inpresif** [comment]
I did change the 
https://api.getgo.com/G2W/rest/v2/

to 
https://api.getgo.com/G2W/rest/v2/

according to the new 06/06/2020 Postman docs, still no luck.

**Comment by dalpras** [comment]
Hi, 
$accessToken must be an instance of \League\OAuth2\Client\Token\AccessToken.  

Just use:  
new \League\OAuth2\Client\Token\AccessToken(['access_token' => $token]);  

Examples are now improved.
This is a third party library for interfacing GotoWebinar. 

For a better understanding of the oauth2 process rely on 
[https://github.com/thephpleague/oauth2-client](https://github.com/thephpleague/oauth2-client)

**Comment by inpresif** [comment]
Thanks Stephano.
